-   id: check-norm
    name: check norm
    description: check norm with norminette app
    entry: norminette
    language: python
    stages: [commit, push, manual]
    types: [text]
    files: \.(h|c)$
-   id: run-unittests
    name: run unit tests from Makefile
    description: launch unit tests from makefile in project.
    language: system
    entry: make
    args: [tests]
    stages: [commit, push, manual]
    types: [text]
    files: \.(h|c)$
